/**
 * Bundles the schematic into a single dependency-free script.
 *
 * The output is committed: GitHub Pages serves a branch verbatim and cannot run
 * a build, so committed output is the only mechanism that works. The same file
 * is inlined into the self-contained artifact by tools/make-artifact.mjs.
 */

import { build } from 'esbuild';
import { statSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const BUNDLE = resolve(ROOT, 'docs/vendor/ltv-schematic.bundle.js');

export async function buildBundle({ quiet = false } = {}) {
  await build({
    entryPoints: [resolve(ROOT, 'src/schematic/main.js')],
    outfile: BUNDLE,
    bundle: true,
    format: 'iife',
    target: 'es2020',
    minify: true,
    // three.js is MIT; the notice has to travel inside the self-contained
    // artifact, so it is kept rather than stripped.
    legalComments: 'eof',
    banner: { js: '/* LTV Mk. II schematic — generated by tools/build.mjs, do not edit. Bundles three.js r185 (MIT). */' },
  });

  const bytes = statSync(BUNDLE).size;
  if (!quiet) console.log(`built docs/vendor/ltv-schematic.bundle.js — ${(bytes / 1024).toFixed(1)} KB`);
  return bytes;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  await buildBundle();
}
